spring.application.name=OficinaMecanicaBackend

# ===========================================
# Configuração do Servidor
# ===========================================
server.port=${PORT:8080}

# ===========================================
# Configuração do Banco de Dados PostgreSQL
# ===========================================
spring.datasource.url=${DB_URL:jdbc:postgresql://caxa.postgres.database.azure.com:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USER:OficinaJT}
spring.datasource.password=${DB_PASS:Faaaah}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================================
# Configuração do JPA / Hibernate
# ===========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
